### ISSUE TITLE
Incorrect results when set is called with no arguments

### ISSUE THREAD

**Issue by brycehanscomb** [3stacks/local-storage-manager#1]
I notice your test suite doesn't cover what happens if I accidentally call `.set()` with no arguments (or with `undefined`). What behaviour do you expect in these edge cases?

**Comment by 3stacks** [comment]
Hi Bryce, 

Please provide a test case for your issue.

Thank you.

**Comment by brycehanscomb** [comment]
Here is a sample:

```js
var ls = require('local-storage-manager');

ls.set(undefined, undefined);

console.log(localStorage);
```

I figured nothing would happen here, but my `localStorage` actually comes out like this:

```
Storage {undefined: "undefined"}
```

Very surprising!

**Comment by 3stacks** [comment]
Thanks for that, I'll get on it right away!

**Comment by 3stacks** [comment]
New version incorporates a check in the set function to see if either the key or data is undefined, if they are, an error is thrown.

Thank you for the heads up.
